In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/Day11_Messy_Company_Employee_Dataset.csv")

print("Dataset loaded")

Dataset loaded

In [3]:
#to print first 5 rows
df.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [4]:
#to print last 5 rows
df.tail()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
152,EMP0132,Manya Rao,Marketing,Content Strategist,30.0,Female,49522.0,0.6,2021-11-25,Delhi,2.0,Remote
153,EMP0073,Karan Kapoor,Customer Success,Customer Success Manager,42.0,MALE,43331.0,1.1,2018-03-23,Jaipur,3.0,Hybrid
154,EMP0124,Saira Kapoor,Engineering,QA Engineer,33.0,Male,94812.0,7.2,2024-06-12,Jaipur,4.0,Hybrid
155,EMP0020,Sara Ali,Sales,Sales Executive,22.0,Female,51745.0,2.4,2020-11-19,NaN,2.0,Office
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

In [5]:
#to get random rows
df.sample(7)

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid
51,EMP0007,Rohan Menon,Engineering,Senior Software Engineer,24.0,Female,79669.0,4.2,2017-02-17,Delhi,4.0,Remote
35,EMP0142,Diya Das,Marketing,Marketing Manager,43.0,Male,NaN,1.2,2021-03-02,Bengaluru,5.0,Hybrid
119,EMP0112,Arjun Mehta,Customer Success,Support Specialist,44.0,Female,102140.0,12.2,2017-09-21,Mumbai,4.0,Hybrid
138,EMP0067,Vivaan Joshi,Engineering,Senior Software Engineer,41.0,Male,88676.0,8.3,2018-09-24,Hyderabad,3.0,Remote
71,EMP0022,Kashish Gupta,Finance,Financial Analyst,41.0,Female,80756.0,2.9,2020-07-13,Chandigarh,3.0,Hybrid
137,EMP0008,Riya Rao,Marketing,Marketing Executive,NaN,Male,63529.0,1.3,2025-05-01,Srinagar,2.0,Remote

In [6]:
print("number of rows: ",df.shape[0])
print("number of cloumns: ",df.shape[1])
print("shape of dataset: ",df.shape)

number of rows:  157
number of cloumns:  12
shape of dataset:  (157, 12)

In [8]:
#to print columnn name
print(df.columns)

Index(['Employee_ID', 'Employee_Name', 'Department', 'Job_Title', 'Age',
       'Gender', 'Annual_Salary', 'Experience_Years', 'Joining_Date', 'City',
       'Performance_Score', 'Work_Mode'],
      dtype='object')

In [9]:
print(df.index)

RangeIndex(start=0, stop=157, step=1)

In [10]:
print(df.dtypes)

Employee_ID           object
Employee_Name         object
Department            object
Job_Title             object
Age                  float64
Gender                object
Annual_Salary        float64
Experience_Years     float64
Joining_Date          object
City                  object
Performance_Score    float64
Work_Mode             object
dtype: object

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [12]:
df.describe()

              Age  Annual_Salary  Experience_Years  Performance_Score
count  153.000000     152.000000        154.000000         154.000000
mean    38.130719   89240.592105          8.990909           3.525974
std      9.361661   22626.172309          4.983874           0.930233
min     21.000000   43331.000000          0.600000           2.000000
25%     30.000000   71198.500000          4.450000           3.000000
50%     39.000000   90046.500000          9.350000           4.000000
75%     46.000000  107328.000000         13.200000           4.000000
max     52.000000  162942.000000         17.400000           5.000000

In [14]:
df.describe(include="all")

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
count,157,157,152,157,153.000000,152,152.000000,154.000000,157,152,154.000000,155
unique,150,130,10,23,NaN,5,NaN,NaN,147,13,NaN,5
top,EMP0075,Nikhil Das,Marketing,Data Scientist,NaN,Male,NaN,NaN,2025-08-17,Chandigarh,NaN,Remote
freq,2,3,23,13,NaN,75,NaN,NaN,2,24,NaN,56
mean,NaN,NaN,NaN,NaN,38.130719,NaN,89240.592105,8.990909,NaN,NaN,3.525974,NaN
std,NaN,NaN,NaN,NaN,9.361661,NaN,22626.172309,4.983874,NaN,NaN,0.930233,NaN
min,NaN,NaN,NaN,NaN,21.000000,NaN,43331.000000,0.600000,NaN,NaN,2.000000,NaN
25%,NaN,NaN,NaN,NaN,30.000000,NaN,71198.500000,4.450000,NaN,NaN,3.000000,NaN
50%,NaN,NaN,NaN,NaN,39.000000,NaN,90046.500000,9.350000,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,46.000000,NaN,107328.000000,13.200000,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,52.000000,NaN,162942.000000,17.400000,NaN,NaN,5.000000,NaN

In [15]:
df.isnull().sum()

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64